### ISSUE TITLE
今天测试报错了，小白，还请帮忙看看是啥原因，地址和端口是没问题的。

### ISSUE THREAD

**Issue by ly1226** [pppyyyccc/streamshield-proxy#3]
root@izj6c9zxcwsd19m9z1cvkhz xteve]# docker logs  streamshield-proxy
StreamShield Proxy is listening on port 4994
所有频道的 M3U 播放列表已生成并保存为 'mytvfree.m3u'。
(node:10) UnhandledPromiseRejectionWarning: FetchError: request to http://x.x.x.x:55002//tptv_proxy.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10) UnhandledPromiseRejectionWarning: FetchError: request to http://x.x.x.x:55002//itv_proxy.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10) UnhandledPromiseRejectionWarning: FetchError: request to http://x.x.x.x:55002//sxg.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:10) UnhandledPromiseRejectionWarning: FetchError: request to http://x.x.x.x:55002//ysp.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:10) UnhandledPromiseRejectionWarning: FetchError: request to http://x.x.x.x:55002//beesport.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:10) UnhandledPromiseRejectionWarning: FetchError: request to http://x.x.x.x:55002//thetv.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
Error fetching or processing 四季: FetchError: request to http://x.x.x.x:55002//4gtv.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002

Error fetching or processing TheTV: FetchError: request to http://x.x.x.x:55002//thetv.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002

Error fetching or processing Beesport 直播源: FetchError: request to http://x.x.x.x:55002//beesport.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002

Error fetching or processing 央视频: FetchError: request to http://x.x.x.x:55002//ysp.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002

Error fetching or processing 蜀小果: FetchError: request to http://x.x.x.x:55002//sxg.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002

Error fetching or processing 中国移动 iTV 平台: FetchError: request to http://x.x.x.x:55002//itv_proxy.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002

Error fetching or processing 江苏移动魔百盒 TPTV: FetchError: request to http://x.x.x.x:55002//tptv_proxy.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002

**Comment by pppyyyccc** [comment]
Error fetching or processing 四季: FetchError: request to http://x.x.x.x:55002//4gtv.m3u failed, reason: connect ETIMEDOUT x.x.x.x:55002
